services:
  app:
    build: .
    env_file: .env
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./scripts:/app/scripts
      - ./data:/app/data
    stdin_open: true
    tty: true
